### ISSUE TITLE
.net内存马注入失败

### ISSUE THREAD

**Issue by Richard-Tang** [x1a0t/Behinder-Source#5]
客户端: windows10

oraclejdk 1.8.0_144

![image](https://user-images.githubusercontent.com/30547741/120058125-49681380-c07b-11eb-90ac-8f2e69ff4c76.png)

服务端: win2008r2 iis7.5

已安装.net扩展

![image](https://user-images.githubusercontent.com/30547741/120058140-5f75d400-c07b-11eb-8c03-2be98d173bdb.png)

**Comment by x1a0t** [comment]
. NET的内存马忽略返回内容，这里输入的路由如果为/abc，内存马实际应该访问/abc/xxx.aspx

**Comment by Richard-Tang** [comment]
> . NET的内存马忽略返回内容，这里输入的路由如果为/abc，内存马实际应该访问/abc/xxx.aspx

可以了，大佬牛逼。
